### ISSUE TITLE
xreader closes when opening an already opened document

### ISSUE THREAD

**Issue by xndrme** [linuxmint/xreader#11]
When is opened a document that is already opened, instead of showing the current window (where the document is already being displayed) xreader silently closes the window, perhaps showing a fast flickering. This is more likely to happen if there are several documents opened at the same time.

**Comment by Cos-mo** [comment]
I cannot reproduce the issue. How many files do you have opened, when the problem occurs?

**Comment by Piiit** [comment]
@xndrme Do you like to beta test the new version, and see if this bug has been fixed?

Steps to do that with a terminal are as follows:
```
mkdir xreader-beta
cd xreader-beta
wget https://github.com/linuxmint/xreader/archive/master.zip
unzip master.zip
cd xreader-master
dpkg-buildpackage
```

This takes some minutes, just wait. At the end it may show some errors about keys and stuff, but don't worry... Now you have all new debian packages inside the xreader-beta folder. To install them type:
```
sudo dpkg -i ../*.deb
```

If you start xreader now, it comes up with the new version. However, this version is beta and may not be as stable as v1.0.8. (BTW, the about dialog still shows 1.0.8 even if it is not the same)

To uninstall it, and the default LM18 version again, just issue: `sudo apt install xreader`.

Cheers!

**Comment by Vahan86** [comment]
I can reproduce this issue in Cinnamon 3.0.7 (Xreader version: 1.0.8)

**Comment by Piiit** [comment]
@Vahan86 Hi, do you like to beta-test? 
If you have time, see instruction above... Would be very welcome :-)
Cheers!

**Comment by ddeath** [comment]
Hey @Piiit I just checked it and on Cinnamon 3.0.7, Linux Mint 18 Sarah 64 bit with xreader-master it does not crash anymore, but it do not work how I would expect it.

Expected behavior is that if I open xreader with same document twice, I will have opened this document twice - I would like to compare them side by side...
Instead the first xreader app stay opened and the second will exit immediately

**Comment by Piiit** [comment]
@ddeath Hi, I tested and you are right. However, most viewers just bring the window to focus for an already opened document. They do not open it again. Tested with Adobe Reader, evince, and xed... The only reader that openes a new window is Okular. 
A workaround for your issue is to open the document, and then click on FILE > OPEN A COPY... or CTRL+N.
Haven't found a command line parameter to set that. Maybe the CLI option is a missing feature.

**Comment by ddeath** [comment]
@Piiit thanks for info. I did not saw that option :)

So I think this can be closed as it is fixed in master :)

**Comment by Piiit** [comment]
@JosephMcc This issue can be closed. Thx

**Comment by xndrme** [comment]
@ddeath @Piiit It's closed :) 
Right now I don't have a way to test it since I'm on a Fedora box... though I still love Linux Mint :)
