### ISSUE TITLE
Picture not displayed

### ISSUE THREAD

**Issue by sphh** [linuxmint/xreader#129]
In the file [notes.pdf](https://github.com/linuxmint/xreader/files/952243/notes.pdf) the picture at the top is shown as a black rectangle. It works in Adobe Reader.

Xreader v1.2.2

**Comment by Piiit** [comment]
Tested: Does not work under...
- Xreader 1.2.2
- Okular 0.24.2
- Evince 3.18.2
- Atril 1.16.1 which uses poppler 0.41

It could therefore be a poppler issue.
- https://bugs.freedesktop.org/show_bug.cgi?id=91415
- https://lists.freedesktop.org/archives/poppler-bugs/2007-August/001215.html 

The latter can be reproduced with `pdfimages notes.pdf x` and `xviewer x-000.pbm` which shows a inverted and flipped image. This could be related as well, because pdfimages uses poppler too.

**Comment by sphh** [comment]
Should I open a bug for poppler then?

**Comment by Piiit** [comment]
@sphh You could. There are several older bug reports, some fixed already with similar descriptions. I do not know if they are related...

**Comment by sphh** [comment]
I just opened a bug with poppler: [https://bugs.freedesktop.org/show_bug.cgi?id=100931](https://bugs.freedesktop.org/show_bug.cgi?id=100931).

**Comment by sphh** [comment]
Upstream reports that this bug is fixed: [https://bugs.freedesktop.org/show_bug.cgi?id=100931#c1](https://bugs.freedesktop.org/show_bug.cgi?id=100931#c1)

Let's hope that the fix trickles down sooner than later ...
