### ISSUE TITLE
Unimplemented action: POPPLER_ACTION_JAVASCRIPT

### ISSUE THREAD

**Issue by rpmoseley** [linuxmint/xreader#144]
When I view PDFs created from a electronic schematic I get a number of warnings when I look at the controlling terminal that invoked the xreader command. One typical  example is to look at the vocore2.sch.pdf file which was downloaded from vocore.io, I have attached the file as an example. I assume that somehow the PDF requires javascript to perform an unstated action, it would be good for some extra information when this message is given - possibly an environment variable.
[vocore2.sch.pdf](https://github.com/linuxmint/xreader/files/1083217/vocore2.sch.pdf)

**Comment by marcelbpunkt** [comment]
I had the same problem when trying to open the pdf version of [Dehne, Sack & Smid: Algorithms and Data Structures. WADS 2003](https://link.springer.com/content/pdf/10.1007%2Fb11837.pdf) (may only be available inside certain university networks due to copyright).

The console showed the same warnings that @rpmoseley mentioned, along with `CRITICAL` messages (about 50 of each) and finally a segfault:
```
** (xreader:25292): WARNING **: 16:51:02.840: Unimplemented action:
POPPLER_ACTION_JAVASCRIPT, please post a bug report on Xreader bug tracker
(https://github.com/linuxmint/xreader/issues) with a testcase.

(xreader:25292): GLib-GObject-CRITICAL **: 16:51:02.840: g_object_unref: assertion
'G_IS_OBJECT (object)' failed

[...]

Segmentation fault (core dumped)
```

The file provided by @rpmoseley however did not cause any trouble in xreader whatsoever (or any other pdf I have ever opened for that matter).

I'm running Linux Mint 19 (Tara) 64 bit on the 4.15.0-32-generic kernel.

**Comment by icarter09** [comment]
@rpmoseley and @marcelbpunkt I'm not sure if I'll be able to provide any useful for why a given pdf failed and what caused that issue. Looking to see if any useful info can be derived from the failure. What I can do those is not cause the messages to keep spawning over and over again. That should stop the segfault as well, though I can't find the pdf of the book you posted @marcelbpunkt to fully test that theory out. 

I'll look further into deriving any info from the failure and also creating a better error message for when the issue is JavaScript related.
