### ISSUE TITLE
Make back/forward buttons grey if they are unclickable

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/xreader#160]
```
 * Xreader version 1.4.4
 * Distribution Mint 18.2
```
I've opened epub file and was clicking back and fwd icons on the panel, cause they were near page number, that was confusing. Xreader needs customizable panel, i would like to have Up and Down buttons on the panel to switch pages

**Comment by Piiit** [comment]
Hi @Yanpas, 
I think you were talking about the history buttons, which are now optional. In addition, the standard page moving buttons have been readded again. I think your issue can be closed, since it is fixed in xreader/master IMO. I am unable to reproduce your issues. For your second idea about configurable icons, I think this is overkill and will not be added. We use default buttons provided by the theme itself....

Is your issue still reproducible?

Best regards,
Piiit
