### ISSUE TITLE
FR: zoomable thumbnails, or thumbnail size pref.

### ISSUE THREAD

**Issue by acornforth** [linuxmint/xreader#164]
```
 * Xreader version 1.4.4
 * Distribution - Mint 18.2
```

**Issue**
page thumbnails are a fixed size

**Steps to reproduce**

**Expected behaviour**
ctrl-mousewheel over sidebar to zoom thumbs would be nice, failing that a preference somewhere that allows user to select a size for thumbnails

**Other information**

**Comment by whiskytroll** [comment]
I agree. I'd like to add that if this is implemented it would be nice to allow smaller thumbnails as well as larger. Sometimes it is preferable to free up screen area but still desirable to have thumbs to help with document navigation.

I'd also like to add another possible "Expected behaviour" if those above wont be implemented (or if this is preferred by the developers): thumb size follow size of sidebar.

**Comment by Piiit** [comment]
@whiskytroll @acornforth This has been implemented in #195
