### ISSUE TITLE
highlight text phrases with textliner (feature request)

### ISSUE THREAD

**Issue by voxspox** [linuxmint/xreader#253]
I would like to see a feature with that I could highlight text phrases and save this annotated PDF again.

**Comment by mickaelalbertus** [comment]
Look at #223 and say if it's what you expect? If you have some good idea of presentation of this functionality, don't hesitate to share with me

**Comment by voxspox** [comment]
ok, this looks quite good. When will this feature be available?

**Comment by voxspox** [comment]
I don't like that the buttons are far off of where my mouse cursor is usually and also that they are in another place, separated from other interaction elements.

I suggest to have the buttons besides the other buttons p.ex:

![39088777-909fa68c-45b8-11e8-9691-e925cdf25ab4](https://user-images.githubusercontent.com/1503565/46309368-7313c880-c5bc-11e8-8062-e5afe1f4e9a5.png)

Buttons:
- create annotation as note box
- mark text with textliner
- mark text with underline
- mark text with strike through
- mark text with wave
- change color of annotation
- remove (last) selected annotation (marking or note box)

**Comment by mickaelalbertus** [comment]
I'm not fan to set the buttons in the toolbar because I do not like when it's too busy. According to me, the location in the annotation sidebar is a good place (like the zoom buttons for the thumbnail sidebar) but I don't know how to set it. But if other people consider it's a good idea I could place in the toolbar.  Why not the remove button I didn't think about it!

**Comment by voxspox** [comment]
Ok, just another remark: If the user is currently not annotating, the buttons could be collapsed.

**Comment by Piiit** [comment]
@voxspox @mickaelalbertus This is supported now since #324. However, the GUI could get some polishing. It is really minimal. I focused on the backend first and just created a single button at the bottom of the annotation sidepane to get access to all those features. Nevertheless, the "hightlight text phrases with textliner" annotations are supported now. Feel free to open another issue, if you have ideas about buttons, annotation workflow, sidepane refactoring or similar things.

**Comment by liriel008** [comment]
Hi! How can I add this to my Xreader?
