### ISSUE TITLE
Shift + Mouse wheel scrolls vertically instead of horizontally

### ISSUE THREAD

**Issue by billscientific** [linuxmint/xreader#275]
```
 * Xreader version 2.0.2
 * Distribution - (Mint 19.1 Cinnamon)
```

**Issue**
**Shift + Mouse wheel** does not scroll horizontally anymore. Instead the document scrolls vertically.

**Steps to reproduce**
1) Open a pdf document in xreader.
2) Zoom in until the document is wider than the window.
3) Shift + mouse wheel

**Expected behaviour**
Document scrolls horizontally.

**Other information**
I think that horizontal scrolling was the behavior in previous versions, and it is a standard in many applications. If my memory plays a trick on me: please consider this to be a feature request. Thank you!

**Comment by prashantraina** [comment]
I'm facing this issue too on Manjaro Cinnamon edition. Could've sworn I used Shift + Mouse wheel to scroll horizontally before.

**Comment by ybolu** [comment]
Same problem here since 19.1 Mate. I am so used to using shift+wheel to scroll horizontally, loosing this ability is not good. Since 19.1 I have been trying combinations with Xreader, Evince, Atril and Marco, Compiz. Latest situation is as follows:
On Linux Mint 19.3, Mate for Horizontal scrolling with shift+wheel 
Xreader + Marco or Compiz = NOT working
Atril + Compiz = WORKING when window has focus but NOT working when window is not focused
Atril + Marco = WORKING on both focused and unfocused window.
