### ISSUE TITLE
move back / forward in hostory using keyboard

### ISSUE THREAD

**Issue by hinxx** [linuxmint/xreader#306]
```
 * Xreader version xreader 1.6.2
 * Distribution - Mint 18.3
```

**Issue**

Can not use keyboard to move back / forward in history.

**Steps to reproduce**

open document, look for key binding.. not found
press alt+left key nothing happens, alt+right key nothing happens,

**Expected behaviour**

Alt + left key : move back in history
Alt + right key: move forward in history

**Other information**

**Comment by nickpj** [comment]
Also present in Xreader version 2.0.2, on Distribution: Linux Mint 19.1 Tessa

Also some keyboards have back & forward buttons (e.g. some Thinkpad laptops, some Microsoft keyboards).  I think it would be useful to include those too, so I will include that request here since it's the same function but just a different key. Support for back & forward keys has now been added to Evince (which I think xreader might be a fork of).

In case it helps, the closed Evince bug report for the above is at: https://bugzilla.gnome.org/show_bug.cgi?id=553892 , and the final patch is at: https://bugzilla.gnome.org/attachment.cgi?id=360845

**Comment by orzechow** [comment]
It would be great to also add support for back/forth buttons that many mice have (e.g. Logitech MX Master).
