### ISSUE TITLE
Booklet Printing

### ISSUE THREAD

**Issue by krsoulsby** [linuxmint/xreader#402]
**Feature Request**

Hello, it would be useful if xReader could print documents as booklets (so when printed two pages per page and double sided the pages are in the collect order when folded.  I know this could be done manually, changing the order the pages are printed but a one click option would be useful.

**Comment by mickaelalbertus** [comment]
I don't think that xreader should include this kind of modification because it is not supported natively by the gtk print dialog. Another solution that I can suggest is to use the applet PdfManager: I will add a functionnality to make booklet from a PDF with pdfbook command. If you want to make a booklet without an applet you can use this command (e.g. pdfbook your_pdf.pdf).

**Comment by alexanderdd** [comment]
pls close this issue here.

yes, it uses the gtk print dialog. In the gnome irc chat they told me that they are not going to change this print dialog. But maybe for future versions of gtk they will? I opened a feature request in the relevant place, feel free to contribute (use your github.com account to log in): https://gitlab.gnome.org/GNOME/gtk/-/issues/2855

this is how adobe does booklet printing: https://helpx.adobe.com/acrobat/kb/print-booklets-acrobat-reader.html

@mickaelalbertus Pdf Manager was has Last Update: 2017-01-16 -- I don't want to use abandoned software. Any other suggestions for linux? (actually already off topic---- can u send me a PM?)

**Comment by mickaelalbertus** [comment]
Yes Adobe can do booklet printing because the print dialog is not the windows native. I hope that they change Gtk to put booklet option.

I didn't do any updates of PDFManager but I'm going to update it!

@alexanderdd : In my profil you'll find my mail if you want to send me a message. We can't send PM in github?

**Comment by krsoulsby** [comment]
Thank you for the feedback, was not aware of pdfbook or pdfmanger, thank you for the tips.  Out side of my expertise but could booklet printing be done with out changing the gtk print dialogue by prepopuling it with double sided print / two pages a side / fliped short side / and most importantly the pages in the correct order for a booklet.  May be too much like hard work, just an idea.  I'm off to use pdfbook now which suits my needs.
