### ISSUE TITLE
Keyboard shortcuts not working on EPUB files

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/xreader#560]
* Xreader version 3.4.3
* Distribution - Mint 21

**Issue**
In Xreader 3.4.3, `Ctrl+PageUp`, `Ctrl+PageDown`, `Shift+Ctrl+PageUp`, `Shift+Ctrl+PageDown`, `Ctrl+Home` and `Ctrl+End` keyboard shortcuts do not work in EPUB files.

**Steps To Reproduce**

1. Open an `.epub` file
2. Press `Ctrl+PageDown` or `Ctrl+End`
3. See error: it does not move to the next/last page.

**Expected behavior**
Shortcuts should work as expected.

**Hardware and mintUpdate**
Is your system all up-to-date? YES

**Additional context**
Using the Menu entries `Go/Next Page`, `Go/Previous Page`, `Go/Next History Item`, `Go/Previous History Item`, `Go/First page` and `Go/Last page` by clicking on them with the mouse cursor works.

**Comment by mtwebster** [comment]
I had a look at this a few days ago - this is caused by the fact that the viewing area is more or less a web page, and doesn't allow shortcuts to be handled properly when it has focus.

A workaround for now is to click into some other ui element, such as the current page box in the toolbar, or the sidebar pulldown selector, so that they receive the keyboard focus. If you do this, the shortcuts will work correctly.

**Comment by spamegg1** [comment]
I understand, clicking on some other UI element works as you described. I guess EPUB renders very differently than PDF huh?

**Comment by eloj** [comment]
> the viewing area is more or less a web page

Is this also why zoom doesn't work on epub? Whatever the reason, it's baffling.

It's a good reader, except that the second most important part (after rendering the contents correctly) doesn't work.

**Comment by spamegg1** [comment]
Can confirm fixed in 3.4.4 update.
